_target_: src.model.components.dit_big_autoencoder.DiTBigAutoencoder
encoder:
  _target_: src.model.components.autoencoder.Encoder
  encoder_dimensions: [3, 128, 256]
decoder:
  _target_: src.model.components.autoencoder.Decoder
  decoder_dimensions: [256, 128, 64, 3]
max_len: ${data.max_len}
scanpath_emb_size: 256
img_feature_dim: 768 # dinov2 base feature size
text_feature_dim: 512 # clip vitb32 text embedding size
spatial_dim: [37, 37]
depth: 6 # number of layers in the transformer
task: unified_model # choose between 'visual_search' and 'unified_model'